### ISSUE TITLE
Page build failure

### ISSUE THREAD

**Issue by zhangyoufu** [zhangyoufu/XuanWu-RSS#4]
```
From: GitHub <support@github.com>
Message-ID: <${GITHUB_REPO}/page-168593417@github.com>
Subject: [${GITHUB_REPO}] Page build failure
Mime-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 7bit
X-Auto-Response-Suppress: All

The page build failed for the `gh-pages` branch with the following error:

Unable to build page. Please try again later.

For information on troubleshooting Jekyll see:

  https://help.github.com/articles/troubleshooting-jekyll-builds

If you have any questions you can submit a request on the Contact GitHub page at https://support.github.com/contact/pages?repo_id=12345678&page_build_id=12345678
```

**Comment by zhangyoufu** [comment]
```
on: page_build

jobs:
  retry:
    if: github.event.build.status == 'errored'
    runs-on: ubuntu-latest
    steps:
    ...
```
